test:
    build: ../
    environment:
        PORT: 3000
        TOKEN_SECRET: "this is a secret"
        NODE_ENV: "development"
        MYSQL_CONNECTION: "mysql://svs:secret@mysql/svs"
        RDS_PORT: "3306"
        RDS_USERNAME: "svs"
        RDS_PASSWORD: "secret"
        RDS_HOSTNAME: "mysql"
        RDS_DB_NAME: "svs"
    links:
        - mysql
    volumes:
        - ../:/srv/www
    working_dir: /srv/www
    dns:
        - 8.8.8.8
        - 9.9.9.9

mysql:
    image: mysql
    ports:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: "root password"
        MYSQL_USER: "svs"
        MYSQL_PASSWORD: "secret"
        MYSQL_DATABASE: "svs"
